### ISSUE TITLE
a room got messed up, not sure how to fix

### ISSUE THREAD

**Issue by kfatehi** [kfatehi/matrix-appservice-facebook#1]
last night i texted a friend "Happy new Year" and it created the room and put her ghost user in it and everything, but she didnt reply for the next few hours or so, and i checked the room and noticed her ghost user wasnt in it. so i "left" and "forgot" the room.

today she replied. what SHOULD have happened is that the room gets setup correctly again, i get joined to it, and her ghost user gets joined to it, and her message shows up.

instead this happened:

![screen shot 2017-01-03 at 11 22 32 am](https://cloud.githubusercontent.com/assets/175305/21619984/fa0a03b0-d1a6-11e6-94d5-c6f8a1c3f343.png)

**Comment by alexmat2on** [comment]
I have very little knowledge of JS/Node, and I don't know exactly how your bridge works, so I might be totally wrong about my idea for why this issue happened. 

However, I noticed that the bridge creates an alias for rooms like `#facebook_CONVERSATIONID`. The first time the room was created, the alias was created and assigned to the room with no problem. But even though you left the Matrix room, the alias is still being used by it.

Later, when she replies, your bridge tries to create a new room with the same alias (because its the same conversation, so the ID didn't change). However, the new room can't use that alias because it's already claimed by the old room you left. 

Could that be the problem?

**Comment by kfatehi** [comment]
Hi @alexmat2on thanks for the analysis. that was in fact the problem and it was fixed last a week or so ago (forgot to close the issue) by carefully going over the order of events and also combining the createAlias call into the createRoom call by passing it the room_alias_name option.

The details of how the bridge works is defined here https://github.com/AndrewJDR/matrix-puppet-bridge
